repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.19.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==25.1.0
