version: 2
formats: all
sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-24.04
  tools:
    # For available versions, see:
    # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
    python: "3.13"  # Keep in sync with .github/workflows/test.yml
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
